# Generated by Django 4.2.2 on 2024-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
