# Generated by Django 4.2.2 on 2024-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_group_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
