# Generated by Django 4.2.2 on 2024-01-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_entry_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="group_id",
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(to="students.student"),
        ),
        migrations.AddField(
            model_name="group",
            name="poll_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.poll",
            ),
            preserve_default=False,
        ),
    ]
