# Generated by Django 4.2.2 on 2024-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_poll_remove_student_group_id_group_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
