# Generated by Django 4.2.2 on 2024-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_group_index_alter_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="expiring",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
