# Generated by Django 4.2 on 2023-05-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_group_alter_student_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="file/")),
            ],
        ),
    ]
