# Generated by Django 4.2 on 2023-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_filemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="img/")),
            ],
        ),
    ]
