# Generated by Django 4.2 on 2023-05-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_imagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="group_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
