# Generated by Django 4.2 on 2023-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_remove_filemodel_group_id_alter_filemodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
