# Generated by Django 4.2 on 2023-05-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_filemodel_group_id_alter_filemodel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filemodel",
            name="group_id",
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="students.group",
            ),
        ),
    ]
