# Generated by Django 4.2 on 2023-06-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0015_alter_filemodel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupScore",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="students.group",
                    ),
                ),
                ("delivery", models.IntegerField()),
                ("content", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Scores",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="students.student",
                    ),
                ),
                ("group_scores", models.ManyToManyField(to="students.groupscore")),
            ],
        ),
    ]
