# Generated by Django 4.2 on 2023-06-04 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0017_choice_entry_vote_choice_poll_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="choice",
        ),
    ]
