# Generated by Django 4.2 on 2023-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0018_remove_vote_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="selection",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
