# Generated by Django 4.2 on 2023-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0019_vote_selection"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("voter", "entry"), name="unique_blocking"
            ),
        ),
    ]
