# Generated by Django 4.2 on 2023-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0020_vote_unique_blocking"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="entry_score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
